-- create
CREATE TABLE CLASSMATES (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (0001, 'Clark', 21, 'Moscow');
INSERT INTO CLASSMATES VALUES (0002, 'Ivan', 26, 'Tver');
INSERT INTO CLASSMATES VALUES (0003, 'Oleg', 31, 'Spb');
INSERT INTO CLASSMATES VALUES (0004, 'Natasha', 18, 'Moscow');
INSERT INTO CLASSMATES VALUES (0005, 'Lena', 30, 'Moscow');


-- fetch 
SELECT * FROM CLASSMATES WHERE age BETWEEN 18 AND 29 AND adress='Moscow';